//! Throughput benchmarks for the SemaGraph classification kernel.
//!
//! Measures, on the same generated data:
//!   * naive single-item classification (`lookup_transition64` + `pack`),
//!   * branchless table classification (`classify_branchless_packed`),
//!   * batch classification (`classify_batch`, plus `classify_batch_simd` when the
//!     `simd` feature is on),
//!   * end-to-end trajectory compression over a 10k-trajectory ensemble.
//!
//! Transitions/sec come from the `transition_classification` group; trajectories/sec
//! and transitions/sec for the ensemble come from `trajectory_compression`.
//!
//! Determinism: all data is generated by a SplitMix64 PRNG seeded with the
//! constants below (recorded so a run is reproducible). No clock- or
//! address-derived randomness is used.
//!
//! Run with: `cargo bench` (add `--features simd` to include the SIMD bench).

use criterion::{black_box, criterion_group, criterion_main, Criterion, Throughput};
use semagraph_core_rs::{
    classify_batch, classify_branchless_packed, compress_trajectory_batch, lookup_transition64,
    pack_transition64,
};

/// Recorded base seed (golden-ratio constant). Reproduces the same data set.
const SEED: u64 = 0x9E37_79B9_7F4A_7C15;
/// Number of random transition pairs classified per benchmark iteration.
const TRANSITION_COUNT: usize = 1 << 16; // 65_536
/// Number of trajectories in the compression ensemble.
const ENSEMBLE_COUNT: usize = 10_000;

struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    fn next_range(&mut self, n: u64) -> u64 {
        self.next_u64() % n
    }
}

fn gen_pairs(count: usize, rng: &mut SplitMix64) -> (Vec<u8>, Vec<u8>) {
    let mut sources = Vec::with_capacity(count);
    let mut targets = Vec::with_capacity(count);
    for _ in 0..count {
        sources.push(rng.next_range(64) as u8);
        targets.push(rng.next_range(64) as u8);
    }
    (sources, targets)
}

fn gen_ensemble(count: usize, rng: &mut SplitMix64) -> Vec<Vec<u8>> {
    let mut ensemble = Vec::with_capacity(count);
    for _ in 0..count {
        let len = 8 + rng.next_range(256 - 8 + 1) as usize; // length in 8..=256
        let mut path = Vec::with_capacity(len);
        for _ in 0..len {
            path.push(rng.next_range(8) as u8);
        }
        ensemble.push(path);
    }
    ensemble
}

fn bench_transition(c: &mut Criterion) {
    let mut rng = SplitMix64::new(SEED);
    let (sources, targets) = gen_pairs(TRANSITION_COUNT, &mut rng);
    let mut out = vec![0u8; TRANSITION_COUNT];

    let mut group = c.benchmark_group("transition_classification");
    group.throughput(Throughput::Elements(TRANSITION_COUNT as u64));

    group.bench_function("naive_per_item", |b| {
        b.iter(|| {
            let mut acc = 0u64;
            #[allow(clippy::needless_range_loop)]
            for i in 0..TRANSITION_COUNT {
                let entry = lookup_transition64(black_box(sources[i]), black_box(targets[i]))
                    .expect("valid six-bit inputs");
                acc ^= pack_transition64(entry);
            }
            black_box(acc)
        })
    });

    group.bench_function("branchless_table", |b| {
        b.iter(|| {
            let mut acc = 0u64;
            #[allow(clippy::needless_range_loop)]
            for i in 0..TRANSITION_COUNT {
                acc ^= classify_branchless_packed(black_box(sources[i]), black_box(targets[i]));
            }
            black_box(acc)
        })
    });

    group.bench_function("batch", |b| {
        b.iter(|| {
            classify_batch(black_box(&sources), black_box(&targets), &mut out);
            black_box(out[TRANSITION_COUNT - 1])
        })
    });

    #[cfg(feature = "simd")]
    group.bench_function("batch_simd", |b| {
        b.iter(|| {
            semagraph_core_rs::classify_batch_simd(
                black_box(&sources),
                black_box(&targets),
                &mut out,
            );
            black_box(out[TRANSITION_COUNT - 1])
        })
    });

    group.finish();
}

fn bench_trajectory(c: &mut Criterion) {
    let mut rng = SplitMix64::new(SEED ^ 0xD1B5_4A32_D192_ED03);
    let ensemble = gen_ensemble(ENSEMBLE_COUNT, &mut rng);
    let refs: Vec<&[u8]> = ensemble.iter().map(|p| p.as_slice()).collect();
    let total_steps: u64 = ensemble
        .iter()
        .map(|p| p.len().saturating_sub(1) as u64)
        .sum();

    let mut net = vec![0u8; ENSEMBLE_COUNT];
    let mut cum = vec![0u32; ENSEMBLE_COUNT];
    let mut endpoint = vec![0u8; ENSEMBLE_COUNT];
    let mut endpoint_hamming = vec![0u8; ENSEMBLE_COUNT];

    let mut group = c.benchmark_group("trajectory_compression");

    group.throughput(Throughput::Elements(ENSEMBLE_COUNT as u64));
    group.bench_function("compress_batch_per_trajectory", |b| {
        b.iter(|| {
            compress_trajectory_batch(
                black_box(&refs),
                &mut net,
                &mut cum,
                &mut endpoint,
                &mut endpoint_hamming,
            );
            black_box(net[ENSEMBLE_COUNT - 1])
        })
    });

    group.throughput(Throughput::Elements(total_steps));
    group.bench_function("compress_batch_per_transition", |b| {
        b.iter(|| {
            compress_trajectory_batch(
                black_box(&refs),
                &mut net,
                &mut cum,
                &mut endpoint,
                &mut endpoint_hamming,
            );
            black_box(cum[ENSEMBLE_COUNT - 1])
        })
    });

    group.finish();
}

criterion_group!(benches, bench_transition, bench_trajectory);
criterion_main!(benches);
