//! Exhaustive cross-implementation parity test.
//!
//! The fixture `tests/fixtures/transition-parity.json` is generated by the
//! TypeScript reference implementation (see
//! `packages/state64-adapter/scripts/generate-parity-fixture.mjs`). It is the
//! authority: this test asserts that the Rust core reproduces every one of the
//! 4096 transitions exactly, on integers, including the packed FFI word.
//!
//! The crate is intentionally dependency-free, so this file contains a tiny
//! purpose-built parser for the fixed, machine-generated schema rather than
//! pulling in serde. It is not a general JSON parser.

use semagraph_core_rs::{
    apply_mutation64, compress_chain64, hamming_distance64, lookup_transition64, pack_transition64,
    transition_index64,
};

const FIXTURE: &str = include_str!("fixtures/transition-parity.json");

#[derive(Debug, Clone, Copy)]
struct Expected {
    source: u8,
    target: u8,
    mutation_mask: u8,
    distance: u8,
    lower_distance: u8,
    upper_distance: u8,
    module_scope_code: u8,
    regime_class_code: u8,
    index: u16,
    packed: u64,
}

/// Extract the integer value of `"key": <number>` that follows `from` in `slice`.
/// `packed` is emitted as a quoted string, so it is read separately.
fn read_u64_field(slice: &str, key: &str) -> u64 {
    let needle = format!("\"{key}\":");
    let start = slice
        .find(&needle)
        .unwrap_or_else(|| panic!("missing field {key} in fixture object"))
        + needle.len();
    let rest = &slice[start..];
    let digits: String = rest
        .chars()
        .skip_while(|c| c.is_whitespace())
        .take_while(|c| c.is_ascii_digit())
        .collect();
    digits
        .parse::<u64>()
        .unwrap_or_else(|_| panic!("non-numeric field {key} in fixture object"))
}

fn read_quoted_u64_field(slice: &str, key: &str) -> u64 {
    let needle = format!("\"{key}\": \"");
    let start = slice
        .find(&needle)
        .unwrap_or_else(|| panic!("missing quoted field {key} in fixture object"))
        + needle.len();
    let rest = &slice[start..];
    let digits: String = rest.chars().take_while(|c| c.is_ascii_digit()).collect();
    digits
        .parse::<u64>()
        .unwrap_or_else(|_| panic!("non-numeric quoted field {key} in fixture object"))
}

fn parse_fixture() -> Vec<Expected> {
    // Each entry object starts at a `"source":` key. Split on that marker.
    let mut entries = Vec::with_capacity(4096);
    let mut search_from = 0usize;
    while let Some(rel) = FIXTURE[search_from..].find("\"source\":") {
        let obj_start = search_from + rel;
        // The object is bounded by the next "source" or end of string; reading
        // individual keys by name within this window is sufficient and robust
        // because the generated schema never nests these keys.
        let next = FIXTURE[obj_start + 1..]
            .find("\"source\":")
            .map(|n| obj_start + 1 + n)
            .unwrap_or(FIXTURE.len());
        let slice = &FIXTURE[obj_start..next];

        entries.push(Expected {
            source: read_u64_field(slice, "source") as u8,
            target: read_u64_field(slice, "target") as u8,
            mutation_mask: read_u64_field(slice, "mutationMask") as u8,
            distance: read_u64_field(slice, "distance") as u8,
            lower_distance: read_u64_field(slice, "lowerDistance") as u8,
            upper_distance: read_u64_field(slice, "upperDistance") as u8,
            module_scope_code: read_u64_field(slice, "moduleScopeCode") as u8,
            regime_class_code: read_u64_field(slice, "regimeClassCode") as u8,
            index: read_u64_field(slice, "index") as u16,
            packed: read_quoted_u64_field(slice, "packed"),
        });

        search_from = next;
    }
    entries
}

#[test]
fn parity_covers_all_4096_transitions() {
    let expected = parse_fixture();
    assert_eq!(
        expected.len(),
        4096,
        "fixture must describe every State64 transition"
    );

    for exp in &expected {
        let entry = lookup_transition64(exp.source, exp.target)
            .unwrap_or_else(|_| panic!("lookup failed for {} -> {}", exp.source, exp.target));

        assert_eq!(entry.source, exp.source);
        assert_eq!(entry.target, exp.target);
        assert_eq!(
            entry.mutation_mask, exp.mutation_mask,
            "mutation mask mismatch for {} -> {}",
            exp.source, exp.target
        );
        assert_eq!(
            entry.distance, exp.distance,
            "distance mismatch for {} -> {}",
            exp.source, exp.target
        );
        assert_eq!(
            entry.lower_distance, exp.lower_distance,
            "lower distance mismatch for {} -> {}",
            exp.source, exp.target
        );
        assert_eq!(
            entry.upper_distance, exp.upper_distance,
            "upper distance mismatch for {} -> {}",
            exp.source, exp.target
        );
        assert_eq!(
            entry.module_scope, exp.module_scope_code,
            "module scope mismatch for {} -> {}",
            exp.source, exp.target
        );
        assert_eq!(
            entry.regime_class, exp.regime_class_code,
            "regime class mismatch for {} -> {}",
            exp.source, exp.target
        );
        assert_eq!(
            entry.index, exp.index,
            "transition index mismatch for {} -> {}",
            exp.source, exp.target
        );
        assert_eq!(
            pack_transition64(entry),
            exp.packed,
            "packed word mismatch for {} -> {}",
            exp.source, exp.target
        );

        // Cross-check the standalone primitives against the same expectations.
        assert_eq!(hamming_distance64(exp.source, exp.target).unwrap(), exp.distance);
        assert_eq!(transition_index64(exp.source, exp.target).unwrap(), exp.index);
    }
}

#[test]
fn parity_primitive_examples() {
    assert_eq!(apply_mutation64(0b000000, 0b100001).unwrap(), 0b100001);
    assert_eq!(hamming_distance64(0b000000, 0b111111).unwrap(), 6);

    let transition = lookup_transition64(0b000000, 0b111111).unwrap();
    assert_eq!(transition.index, 63);
    assert_eq!(transition.mutation_mask, 0b111111);
    assert_eq!(transition.distance, 6);

    // 0b101010 = 42, 0b010101 = 21, index = 42 * 64 + 21 = 2709.
    assert_eq!(transition_index64(0b101010, 0b010101).unwrap(), 2709);

    let chain = compress_chain64(&[0b000000, 0b100000, 0b101000, 0b101010]).unwrap();
    assert_eq!(chain.net_mutation_mask, 0b101010);
    assert_eq!(chain.cumulative_distance, 3);
}
