//! Trajectory shape/projection parity against the TypeScript reference.
//!
//! The fixture `tests/fixtures/shape-parity.json` is generated by the reference
//! implementation in `@semagraph/kernel`'s `shapes.ts` (see
//! `packages/state64-adapter/scripts/generate-shape-parity-fixture.mjs`). It is
//! the authority: this test asserts the Rust port reproduces, for every Q3
//! trajectory, the run-collapsed shape, the dwell vector, and each declared
//! projection exactly, on integers.
//!
//! As with `parity.rs`, the crate is dependency-free, so this is a tiny
//! purpose-built parser for the fixed machine-generated schema, not a general
//! JSON parser.

use semagraph_core_rs::{compress_trajectory_batch, project_trajectory};

const FIXTURE: &str = include_str!("fixtures/shape-parity.json");

#[derive(Debug, Clone)]
struct Expected {
    states: Vec<u8>,
    shape: Vec<u8>,
    dwell: Vec<u32>,
    net_mutation: u8,
    endpoint: u8,
    endpoint_hamming: u8,
    cumulative_distance: u32,
}

/// Read `"key": <number>` as an unsigned integer.
fn read_u64_field(slice: &str, key: &str) -> u64 {
    let needle = format!("\"{key}\":");
    let start = slice
        .find(&needle)
        .unwrap_or_else(|| panic!("missing field {key} in fixture object"))
        + needle.len();
    let rest = &slice[start..];
    rest.chars()
        .skip_while(|c| c.is_whitespace())
        .take_while(|c| c.is_ascii_digit())
        .collect::<String>()
        .parse::<u64>()
        .unwrap_or_else(|_| panic!("non-numeric field {key} in fixture object"))
}

/// Read `"key": [ n, n, ... ]` as a list of unsigned integers. The schema never
/// nests arrays inside these fields, so reading to the first `]` is sufficient.
fn read_array_field(slice: &str, key: &str) -> Vec<u64> {
    let needle = format!("\"{key}\":");
    let start = slice
        .find(&needle)
        .unwrap_or_else(|| panic!("missing array {key} in fixture object"))
        + needle.len();
    let rest = &slice[start..];
    let open = rest
        .find('[')
        .unwrap_or_else(|| panic!("missing '[' for {key}"));
    let close = rest[open..]
        .find(']')
        .unwrap_or_else(|| panic!("missing ']' for {key}"))
        + open;
    rest[open + 1..close]
        .split(',')
        .filter_map(|token| {
            let trimmed = token.trim();
            if trimmed.is_empty() {
                None
            } else {
                Some(
                    trimmed
                        .parse::<u64>()
                        .unwrap_or_else(|_| panic!("non-numeric element in {key}")),
                )
            }
        })
        .collect()
}

fn parse_fixture() -> Vec<Expected> {
    let mut entries = Vec::new();
    let mut search_from = 0usize;
    // Each entry object starts at a `"states":` key.
    while let Some(rel) = FIXTURE[search_from..].find("\"states\":") {
        let obj_start = search_from + rel;
        let next = FIXTURE[obj_start + 1..]
            .find("\"states\":")
            .map(|n| obj_start + 1 + n)
            .unwrap_or(FIXTURE.len());
        let slice = &FIXTURE[obj_start..next];

        entries.push(Expected {
            states: read_array_field(slice, "states")
                .into_iter()
                .map(|v| v as u8)
                .collect(),
            shape: read_array_field(slice, "shape")
                .into_iter()
                .map(|v| v as u8)
                .collect(),
            dwell: read_array_field(slice, "dwell")
                .into_iter()
                .map(|v| v as u32)
                .collect(),
            net_mutation: read_u64_field(slice, "netMutation") as u8,
            endpoint: read_u64_field(slice, "endpointCode") as u8,
            endpoint_hamming: read_u64_field(slice, "endpointHamming") as u8,
            cumulative_distance: read_u64_field(slice, "cumulativeDistance") as u32,
        });

        search_from = next;
    }
    entries
}

#[test]
fn shape_parity_matches_reference() {
    let expected = parse_fixture();
    assert!(
        expected.len() >= 200,
        "fixture should describe a substantial set of trajectories, got {}",
        expected.len()
    );

    for exp in &expected {
        let projection = project_trajectory(&exp.states);
        assert_eq!(
            projection.shape, exp.shape,
            "shape mismatch for {:?}",
            exp.states
        );
        assert_eq!(
            projection.dwell, exp.dwell,
            "dwell mismatch for {:?}",
            exp.states
        );
        assert_eq!(
            projection.net_mutation, exp.net_mutation,
            "net mutation mismatch for {:?}",
            exp.states
        );
        assert_eq!(
            projection.endpoint, exp.endpoint,
            "endpoint mismatch for {:?}",
            exp.states
        );
        assert_eq!(
            projection.endpoint_hamming, exp.endpoint_hamming,
            "endpoint hamming mismatch for {:?}",
            exp.states
        );
        assert_eq!(
            projection.cumulative_distance, exp.cumulative_distance,
            "cumulative distance mismatch for {:?}",
            exp.states
        );
    }
}

#[test]
fn shape_parity_batch_matches_reference() {
    let expected = parse_fixture();
    let paths: Vec<&[u8]> = expected.iter().map(|e| e.states.as_slice()).collect();
    let n = paths.len();

    let mut net = vec![0u8; n];
    let mut cum = vec![0u32; n];
    let mut endpoint = vec![0u8; n];
    let mut endpoint_hamming = vec![0u8; n];
    compress_trajectory_batch(
        &paths,
        &mut net,
        &mut cum,
        &mut endpoint,
        &mut endpoint_hamming,
    );

    for (i, exp) in expected.iter().enumerate() {
        assert_eq!(
            net[i], exp.net_mutation,
            "batch net mismatch for {:?}",
            exp.states
        );
        assert_eq!(
            cum[i], exp.cumulative_distance,
            "batch cumulative mismatch for {:?}",
            exp.states
        );
        assert_eq!(
            endpoint[i], exp.endpoint,
            "batch endpoint mismatch for {:?}",
            exp.states
        );
        assert_eq!(
            endpoint_hamming[i], exp.endpoint_hamming,
            "batch endpoint hamming mismatch for {:?}",
            exp.states
        );
    }
}
